#-------------------------------------------------------------------------
# This adds additional associations to
# https://github.com/gramps-project/addons-source/blob/master/SyncAssociations/syncAssociations.py
# Primarily made for tracking associations between Sims of the game, The Sims 3
# Copy & Paste this file over the Constants Section
#-------------------------------------------------------------------------
#
# Constants
# https://gramps-project.org/wiki/index.php/Roles,_Relationships_%26_Associations
#
#-------------------------------------------------------------------------
ASSOC_LOOKUP = {
#----------Family
"DNA": "DNA",
"Ancestor": "Descendant",
"Descendant": "Ancestor",
"Family Member": "Family Member",
"Blood Relative": "Blood Relative",
#----------Chosen Family
"Godparent": "Godchild",
"Godchild": "Godparent",
#----------Guardian
"Guardian": "Ward",
"Ward": "Guardian",
"Foster Parent": "Foster Child",
"Foster Child": "Foster Parent",
"Adoptive Parent": "Adopted Child",
"Adopted Child": "Adoptive Parent",
"Custodian": "Charge",
"Charge": "Custodian",
"Surrogate Parent": "Surrogate Child",
"Surrogate Child": "Surrogate Parent",
#----------Legal
"Beneficiary": "Executor",
"Executor": "Beneficiary",
"Trustee": "Trust Beneficiary",
"Trust Beneficiary": "Trustee",
"Testator": "Heir",
"Heir": "Testator",
"Will Creator": "Legacy Receiver",
"Legacy Receiver": "Will Creator",
"Estate Owner": "Estate Recipient",
"Estate Recipient": "Estate Owner",
#----------Named
"Namesake": "Named After",
"Named After": "Namesake",
"Honorary Name": "Honoree",
"Honoree": "Honorary Name",
"Legacy Name": "Legacy Holder",
"Legacy Holder": "Legacy Name",
"Dedicatee": "Dedicator",
"Dedicator": "Dedicatee",
#----------Romantic
"Romantic Interest": "Romantic Interest",
"Love Interest": "Love Interest",
"Significant Other": "Significant Other",
"Deceased Spouse": "Surviving Spouse",
"Surviving Spouse": "Deceased Spouse",
"Spouse": "Spouse",
"Partner": "Partner",
"Romantic Partner": "Romantic Partner",
"Soulmate": "Soulmate",
"Affair": "Affair",
"Lover": "Lover",
"Dating": "Dating",
"Engaged": "Engaged",
"Ex-Engaged": "Ex-Engaged",
"Ex": "Ex",
"Ex-Partner": "Ex-Partner",
#----------Friendships
"Companion": "Companion",
"Acquaintance": "Acquaintance",
"Friend": "Friend",
"Close Friend": "Close Friend",
"Good Friend": "Good Friend",
"Best Friend": "Best Friend",
"Best Friend Forever": "Best Friend Forever",
"Distant Friend": "Distant Friend",
"Old Friend": "Old Friend",
"Childhood Friend": "Childhood Friend",
"Casual Friend": "Casual Friend",
"Trusted Friend": "Trusted Friend",
"Confidant": "Confidant",
"Online Friend": "Online Friend",
"Online Correspondent": "Online Correspondent",
#----------Adversarial
"Ex-Friend": "Ex-Friend",
"Disliked": "Disliked",
"Foe": "Foe",
"Enemy": "Enemy",
"Old Enemy": "Old Enemy",
"Nemesis": "Nemesis",
"Adversary": "Adversary",
"Antagonist": "Protagonist",
"Protagonist": "Antagonist",
"Competitor": "Competitor",
"Opponent": "Opponent",
"Legal Opponent": "Legal Opponent",
"Political Opponent": "Political Opponent",
"Professional Opponent": "Professional Opponent",
"Rival": "Rival",
"Academic Rival": "Academic Rival",
"Artist Rival": "Artist Rival",
"Athletic Rival": "Athletic Rival",
"Business Rival": "Business Rival",
"Celebrity Rival": "Celebrity Rival",
"Competitive Rival": "Competitive Rival",
"Cultural Rival": "Cultural Rival",
"Friendly Rival": "Friendly Rival",
"Legal Rival": "Legal Rival",
"Philosophical Rival": "Philosophical Rival",
"Political Rival": "Political Rival",
"Professional Rival": "Professional Rival",
"Research Rival": "Research Rival",
"Romantic Rival": "Romantic Rival",
"Team Rival": "Team Rival",
"Tech Rival": "Tech Rival",
#----------Creature Companions
"Familiar Bond": "Familiar Bond",
"Magical Bond": "Magical Bond",
"Spiritual Bond": "Spiritual Bond",
"Creature Companion": "Creature Caretaker",
"Creature Caretaker": "Creature Companion",
"Pet": "Pet Owner",
"Pet Owner": "Pet",
"Summoner": "Summoned Creature",
"Summoned Creature": "Summoner",
#----------Supernatural
"Spirit Guide": "Guided Spirit",
"Guided Spirit": "Spirit Guide",
"Mystical Mentor": "Mystical Apprentice",
"Mystical Apprentice": "Mystical Mentor",
"Sorcerer Mentor": "Sorcerer Apprentice",
"Sorcerer Apprentice": "Sorcerer Mentor",
"Spellcaster Mentor": "Spellcaster Apprentice",
"Spellcaster Apprentice": "Spellcaster Mentor",
"Fairy Apprentice": "Fairy Mentor",
"Fairy Mentor": "Fairy Apprentice",
"Witch Apprentice": "Witch Mentor",
"Witch Mentor": "Witch Apprentice",
"Mermaid Mentor": "Mermaid Apprentice",
"Mermaid Apprentice": "Mermaid Mentor",
"Genie": "Genie Summoner",
"Genie Summoner": "Genie",
"Imaginary Friend": "Imaginary Friend Owner",
"Imaginary Friend Owner": "Imaginary Friend",
"Vampire Ascendant": "Vampire Descendant",
"Vampire Descendant": "Vampire Ascendant",
"Alien Pollinator": "Alien Offspring",
"Alien Offspring": "Alien Pollinator",
"Alien Abductor": "Alien Abductee",
"Alien Abductee": "Alien Abductor",
"Werewolf Alpha": "Werewolf Pack Member",
"Werewolf Pack Member": "Werewolf Alpha",
"Plumbot": "Plumbot Creator",
"Plumbot Creator": "Plumbot",
"Simbot": "Simbot Creator",
"Simbot Creator": "Simbot",
"Zombie Giver": "Zombie Recipient",
"Zombie Recipient": "Zombie Giver",
"Vampire Giver": "Vampire Recipient",
"Vampire Recipient": "Vampire Giver",
"Werewolf Giver": "Werewolf Recipient",
"Werewolf Recipient": "Werewolf Giver",
"Curse Giver": "Curse Recipient",
"Curse Recipient": "Curse Giver",
#----------Correspondence
"Email Correspondent": "Email Correspondent",
"Mail Correspondent": "Mail Correspondent",
"Letter Recipient": "Letter Writer",
"Letter Writer": "Letter Recipient",
"Message Sender": "Message Receiver",
"Message Receiver": "Message Sender",
"Correspondent": "Correspondent",
"Penpal": "Penpal",
#----------Education
"Mentor": "Protégé",
"Protégé": "Mentor",
"Instructor": "Pupil",
"Pupil": "Instructor",
"Tutor": "Tutee",
"Tutee": "Tutor",
"Advisor": "Advisee",
"Advisee": "Advisor",
"Teacher": "Student",
"Student": "Teacher",
"Lab Mate": "Lab Mate",
"Lab Partner": "Lab Partner",
"Research Partner": "Research Partner",
"Schoolmate": "Schoolmate",
"Classmate": "Classmate",
"Teammate": "Teammate",
"Collaborator": "Collaborator",
"Peer": "Peer",
"Senior": "Junior",
"Junior": "Senior",
"Senpai": "Kouhai",
"Kouhai": "Senpai",
#----------Professional, Career
"Employer": "Employee",
"Employee": "Employer",
"Coworker": "Coworker",
"Co-worker": "Co-worker",
"Colleague": "Colleague",
"Business Associate": "Business Associate",
"Associate": "Associate",
"Sponsor": "Sponsee",
"Sponsee": "Sponsor",
"Leader": "Supporter",
"Supporter": "Leader",
"Ally": "Ally",
"Artist": "Patron",
"Patron": "Artist",
#----------Medical
"Healthcare Provider": "Patient",
"Patient": "Healthcare Provider",
"Caregiver": "Care Recipient",
"Care Recipient": "Caregiver",
#----------Residential
"Neighbour": "Neighbour",
"Household Member": "Household Member",
"Apartment Mate": "Apartment Mate",
"Apartment Partner": "Apartment Partner",
"Flatmate": "Flatmate",
"Co-Tenant": "Co-Tenant",
"Housemate": "Housemate",
"Roommate": "Roommate",
"Resident Advisor": "Dorm Resident",
"Dorm Resident": "Resident Advisor",
"Property Owner": "Occupant",
"Occupant": "Property Owner",
"Building Manager": "Resident",
"Resident": "Building Manager",
"Landlord": "Tenant",
"Tenant": "Landlord",
#----------Funerary
"Pallbearer": "Pallbearer for",
"Pallbearer for": "Pallbearer"
}
WIKI_HELP_PAGE = 'https://gramps-project.org/wiki/index.php/Addon:SyncAssociation'
